name: Build and Deploy Static Assets

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        django-version:
          - "5.1.10"
          - "4.2.17"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and run Docker container
        env:
          DJANGO_VERSION: ${{ matrix.django-version }}
          RCLONE_CONFIG_DEFAULT_PROVIDER: Cloudflare
          RCLONE_CONFIG_DEFAULT_ENDPOINT: ${{ secrets.RCLONE_CONFIG_DEFAULT_ENDPOINT }}
        run: |
          echo "${{ secrets.RCLONE_ACCESS_KEY_ID }}" > /tmp/rclone_access_key_id
          echo "${{ secrets.RCLONE_SECRET_ACCESS_KEY }}" > /tmp/rclone_secret_access_key

          docker build \
            --build-arg DJANGO_VERSION="${DJANGO_VERSION}" \
            --build-arg RCLONE_CONFIG_DEFAULT_PROVIDER="${RCLONE_CONFIG_DEFAULT_PROVIDER}" \
            --build-arg RCLONE_CONFIG_DEFAULT_ENDPOINT="${RCLONE_CONFIG_DEFAULT_ENDPOINT}" \
            --secret id=rclone_access_key_id,src=/tmp/rclone_access_key_id \
            --secret id=rclone_secret_access_key,src=/tmp/rclone_secret_access_key \
            --progress=plain \
            -t django-admin-cdn:${{ matrix.django-version }} .

          rm -f /tmp/rclone_access_key_id /tmp/rclone_secret_access_key
